### ISSUE TITLE
Crash on save

### ISSUE THREAD

**Issue by some0nenew** [Makhber/makhber#5]
**Describe the bug**

When I add a constant function (y = 2.1) to a plot (with some prior data) and try to save, the whole program closes without saving.

**Expected behavior**

Normal save, no crash

**Desktop**
 - OS: Manjaro Linux
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.14.21-2-MANJARO (64-bit)
Graphics Platform: X11
Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2
 - Version: 0.9.4.3

**Comment by MehdiChinoune** [comment]
Thanks for the report. I have pushed a fix to `qwt5` branch.
From where did you install it? (snap, flatpak...)

**Comment by some0nenew** [comment]
I got it from Flatpak
