### ISSUE TITLE
Unable to open old Projekt

### ISSUE THREAD

**Issue by some0nenew** [Makhber/makhber#6]
Unable to open existing Projekt
Tried to open it by double clicking the *.sciprj file. Whole Program crashes without error.
Tried to open in via "ctrl"+"o". get an error "Error std::bad_alloc sending event 11QMouseEvent to object  "5QMenu""

**Desktop**
 - OS: Linux - Manjaro
 - Version: 0.9.5 via flatpack

Here my file, maybe that helps. And yes i know that's one big cluster****...
[Datenausarbeitung.zip](https://github.com/Makhber/makhber/files/8033608/Datenausarbeitung.zip)
Nothing major is lost, just wanted to update some graphs but overall thats not something that should happen...

**Comment by MehdiChinoune** [comment]
Did you install it from flathub-beta repo?

**Comment by some0nenew** [comment]
Makhber                                 com.github.makhber.Makhber                              0.9.5                 stable                system

**Comment by MehdiChinoune** [comment]
I couldn't reproduce the issue on Ubuntu 20.04

**Comment by MehdiChinoune** [comment]
@some0nenew Do you still encounter this issue?

**Comment by some0nenew** [comment]
So far i could not reproduce this problem anymore, so lets hope that was an error on my side
